FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/client/package.json apps/client/package-lock.json ./apps/client/
RUN npm ci

COPY . ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--workspace=@rusniped/web", "--", "--host", "0.0.0.0"]
